GET http://{{host}}:{{port}}/fetch/alerts
Content-Type: application/json

{
  "ws_user_key": "{{ws_user_key}}",
  "ws_org_token": "{{ws_org_token}}",
  "ws_scope_token": "{{ws_scope_token}}",
  "ws_url": "{{ws_url}}"
}
###
GET http://{{host}}:{{port}}/fetch/lib_vulnerabilities
Content-Type: application/json

{
  "ws_user_key": "{{ws_user_key}}",
  "ws_org_token": "{{ws_org_token}}",
  "ws_scope_token": "{{ws_scope_token}}",
  "ws_url": "{{ws_url}}"
}
###
